### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by sunny910317** [owendswang/Download-Weibo-Images-Videos#1]
1、本次更新后无法保存为自定的文件名称，只会保存为{original} - 原文件名
2、现在一条微博可以发同时发图片和视频，且可以同时发多个视频，但是以本脚本保存时只能保存第一个视频

**Comment by owendswang** [comment]
我更新一下，第一个问题可以修复。
第二个问题，我再琢磨琢磨。

**Comment by owendswang** [comment]
你说的第二个问题，的确有的微博是可以这样发，但是我找到的，只有部分在app和微信网页里能够显示出多视频和视频图片混合显示，网页端依然只显示一个视频，可能这个功能在网页端还没铺开这个功能。
如果有例外，我建议列出一个或几个这样的微博链接，方便我分析一下，也对比一下网页和客户端的是否都能同意显示出多视频或视频图片混合。

**Comment by sunny910317** [comment]
看了两天，目前没有这样的例外，可能还得等官方把网页端的显示方式更新
谢谢脚本更新，辛苦了

**Comment by owendswang** [comment]
好的，那等网页端有变化了我再更新。

**Comment by sunny910317** [comment]
你好，网页端的显示方式更新了

**Comment by owendswang** [comment]
https://github.com/owendswang/Download-Weibo-Images-Videos/commit/57e72506ba8129742fca7a95c83b0341063b2772

嗯，刚更新了，v0.9版本可以了。有问题的话，我再改。

**Comment by sunny910317** [comment]
可以了，谢谢。
另外有个问题请教，
保存livephoto时，文件会分为图片格式和视频格式，但视频格式保存后不会有副文件名，需要手动加上，是我在油猴的什么设置不对吗？

**Comment by owendswang** [comment]
副文件名是指什么？文件后缀？.mov？

**Comment by owendswang** [comment]
副文件名是指什么？文件后缀？.mov？

**Comment by sunny910317** [comment]
对的文件后缀。tampermonkey的设定→下载BETA 我已经加了mov，但还是不行

**Comment by owendswang** [comment]
下载模式选“原生”，文件扩展名白名单里随便找个位置加上mov，我的那一行是这样的`/\.(avi|mkv|flv|divx|mpe?g|webm|mov|mp4)$/`

**Comment by sunny910317** [comment]
就是这么设置的，还是不行

**Comment by owendswang** [comment]
所有的都不行？是什么页面，搜索页面还是登陆后的页面？给个链接？

**Comment by sunny910317** [comment]
https://weibo.com/5760083136/MycevwuSx

**Comment by owendswang** [comment]
哦，这就是普通的页面，没问题的哇，我是没登录下载的。
跟环境有关？啥系统、啥浏览器、啥插件？
![1111](https://user-images.githubusercontent.com/9076865/226563151-ebe8d83e-bf30-4431-9337-d2bae6694dd6.PNG)

**Comment by sunny910317** [comment]
win10、chrome浏览器、tampermonkey

**Comment by owendswang** [comment]
我也是一样的环境，没问题的啊。
下载是设置里文件名最后有".{ext}”吧，有的话就会有后缀的。
Tampermonkey的高级设置里添加mov后，有点保存吧。
另外windows资源管理器，默认是隐藏后缀名的，自己在设置里改了才能看到后缀名。
![Capture](https://user-images.githubusercontent.com/9076865/226602878-45acbacb-3d12-4d37-84f2-ab79212507fa.PNG)

**Comment by sunny910317** [comment]
都有的，而且单单只有livephoto的mov文件没有后缀，保存一般视频和图片的时候都很正常
实在是找不到其他问题了，才询问的。
我试试重新安装浏览器，再重装扩展和脚本吧
谢谢了
