### ISSUE TITLE
能否支持无水印下载

### ISSUE THREAD

**Issue by Yourrrrlove** [owendswang/Download-Weibo-Images-Videos#3]
能否支持无水印下载图片

![image](https://github.com/owendswang/Download-Weibo-Images-Videos/assets/98163348/259032b5-0a56-424b-a3e5-dc0d630c65a1)

第462行，用正则将 square|thumb150|orj360|orj480|mw690|mw1024|mw2048|small|bmiddle|large|mw2000|thumbnail|thumb150|mw600|mw690|mw1024|small|bmiddle|orj360|thumb180|mw2000 替换为'oslarge'，但下载下来仍然是有水印的图。

**Comment by owendswang** [comment]
我以为这个功能是用户自己设置的，如果他设置了上传的图片不包含水印，那就没有水印，默认是带水印的。
如果你试了不行，那应该就是不行吧。

**Comment by owendswang** [comment]
我也试了，不行，那就的确这个方法不行，跟上传者自己的设置有关。
